Adding bound action to Table Api page to automatically add all fields
microsoft/bc2adls pull request #132
Opened 2023-08-16 17:44 UTC by RonKoppelaar

Adding a bound action called: addAllFields, which could be invoked from the API page ./adlseTables

2023-08-17 17:34 UTC, Bertverbeek4PS requested changes

2023-08-17 17:34 UTC, Bertverbeek4PS commented on businessCentral/src/ADLSETableAPI.Page.al
> +    end;
The var can be removed and also the repeat function.
You can use:
rec.AddAllFields()

2023-08-17 18:05 UTC, RonKoppelaar commented on businessCentral/src/ADLSETableAPI.Page.al
> +    end;
Fixed code with proposal

2023-08-17 18:13 UTC, Bertverbeek4PS approved these changes

2023-08-23 07:05 UTC, Arthurvdv commented on businessCentral/src/ADLSETable.Table.al
> +        if ADLSEFields.FindSet() then
Setting the parameter to true on ```if ADLSEFields.FindSet(true) then``` would increase performance.

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-findset-boolean-method#parameters

2026-04-29 07:32 UTC, closed without merging