Add TableCaption/Entity to Telemetry Logs
microsoft/bc2adls pull request #66
Opened 2022-11-23 17:01 UTC by JulianSchmidtke

At the moment the Table Caption is only used in the Start-Export Event.  We have no solution to see when the export for a given table started and stopped. With this change you can:
1. See when the export for a given Table started
2. See how many datasets to export are found 
4. See when the export for a given Table finished

This way you can monitor the mean export time per Table and can react to slower exports or find missing SystemModifiedAt keys.

Fixes #65

2022-11-24 08:02 UTC, JulianSchmidtke commented
@microsoft-github-policy-service agree [company="GWS mbH"]

2022-11-24 08:02 UTC, JulianSchmidtke commented
@microsoft-github-policy-service agree company="GWS mbH"

2022-11-28 10:43 UTC, DuttaSoumya requested changes
Good telemetry enrichment- looks ready to go. I made an additional comment for consistency sake. Kindly take a look :-)

2022-11-28 10:43 UTC, DuttaSoumya commented on businessCentral/src/ADLSEExecute.Codeunit.al
> +
Great idea! why not do the same also at `local procedure ExportTableDeletes`? adding CustomDimenions to line 221?

2022-11-28 10:44 UTC, DuttaSoumya commented on businessCentral/src/ADLSEExecute.Codeunit.al
> +
Also, please increment the version at app.json

2022-12-02 07:05 UTC, JulianSchmidtke commented on businessCentral/src/ADLSEExecute.Codeunit.al
> +
Done!

2022-12-06 14:52 UTC, DuttaSoumya commented on businessCentral/src/ADLSEExecute.Codeunit.al
> +                EntityCount := Format(Rec.Count());
`EntityCount := Format(ADLSEDeletedRecord.Count());`
instead of 
`EntityCount := Format(Rec.Count());`

2022-12-09 10:23 UTC, merged